// 사용자와 상호작용하는건 클라이언트 컴포넌트, 그냥 보여주는건 서버 컴포턴트
// next JS 에서는 기본적으로 서버 컴포넌트라 생각한다. use client 쓸것
// client 실행 : npm run dev
// json서버실행 : npx json-server --watch --port 9999 db.json
// 서버컴포넌트는 useEffect useState 필요없음. 되도록 서버컴포넌트화하셈
// uswParams등 일부기능 클라이언트 컴포넌트 써야한다면 따로 파일파서 import할것

import Link from 'next/link'
import "./globals.css";
import { Control } from './Control';

export const metadata = {
  title: "web tutorials",
  description: "Generated by nowaveosu",
};

export default async function RootLayout({ children }) {
  const resp = await fetch(process.env.NEXT_PUBLIC_API_URL+'topics', {cache: 'no-store'});
  const topics = await resp.json();
  return (
    <html>
      <body>
        <h1><Link href="/">WEB</Link></h1>
        <ol>
          {topics.map((topic) =>{
            return <li key={topic.id}><Link href={`/read/${topic.id}`}>{topic.title}</Link></li>
          })
          }
        </ol>
          {children}
          <Control />
      </body>
    </html>
  );
}
